from django.urls import path

from . import views


urlpatterns = [
    path("login", views.login_page),
    path("login/", views.login_page, name="login"),
    path("logout", views.logout_view),
    path("logout/", views.logout_view, name="logout"),
    path("admin-panel", views.admin_panel),
    path("admin-panel/", views.admin_panel, name="admin_panel"),
    path("admin-users", views.admin_users),
    path("admin-users/", views.admin_users, name="admin_users"),
    path("admin-users/new", views.admin_user_form),
    path("admin-users/new/", views.admin_user_form, name="admin_user_new"),
    path("admin-users/<int:user_id>/edit", views.admin_user_form),
    path("admin-users/<int:user_id>/edit/", views.admin_user_form, name="admin_user_edit"),
    path("admin-users/<int:user_id>/delete", views.admin_user_delete),
    path("admin-users/<int:user_id>/delete/", views.admin_user_delete, name="admin_user_delete"),
    path("admin-groups", views.admin_groups),
    path("admin-groups/", views.admin_groups, name="admin_groups"),
    path("admin-groups/new", views.admin_group_form),
    path("admin-groups/new/", views.admin_group_form, name="admin_group_new"),
    path("admin-groups/<int:group_id>/edit", views.admin_group_form),
    path("admin-groups/<int:group_id>/edit/", views.admin_group_form, name="admin_group_edit"),
    path("admin-groups/<int:group_id>/delete", views.admin_group_delete),
    path("admin-groups/<int:group_id>/delete/", views.admin_group_delete, name="admin_group_delete"),
    path("set-dept/", views.set_dept_view, name="set_dept"),
    path("", views.root_redirect, name="root"),
    path("inventory", views.inventory_page),
    path("inventory/", views.inventory_page, name="inventory"),
    path("master", views.master_page),
    path("master/", views.master_page, name="master"),
    path("master/create", views.master_create),
    path("master/create/", views.master_create, name="master_create"),
    path("master/<int:item_id>/edit", views.master_edit_submit),
    path("master/<int:item_id>/edit/", views.master_edit_submit, name="master_edit"),
    path("master/<int:item_id>/delete", views.master_delete),
    path("master/<int:item_id>/delete/", views.master_delete, name="master_delete"),
    path("master/<int:item_id>/dispose", views.master_dispose),
    path("master/<int:item_id>/dispose/", views.master_dispose, name="master_dispose"),
    path("master/bulk-delete", views.master_bulk_delete),
    path("master/bulk-delete/", views.master_bulk_delete, name="master_bulk_delete"),
    path("master/bulk-dispose", views.master_bulk_dispose),
    path("master/bulk-dispose/", views.master_bulk_dispose, name="master_bulk_dispose"),
    path("master/upload-template", views.download_master_upload_template),
    path("master/upload-template/", views.download_master_upload_template, name="master_upload_template"),
    path("master/upload-preview", views.upload_master_preview),
    path("master/upload-preview/", views.upload_master_preview, name="master_upload_preview"),
    path("master/upload-confirm", views.upload_master_confirm),
    path("master/upload-confirm/", views.upload_master_confirm, name="master_upload_confirm"),
    path("inbound", views.inbound_page),
    path("inbound/", views.inbound_page, name="inbound"),
    path("inbound/bulk-create", views.inbound_bulk_create),
    path("inbound/bulk-create/", views.inbound_bulk_create, name="inbound_bulk_create"),
    path("inbound/bulk-preview", views.inbound_bulk_preview),
    path("inbound/bulk-preview/", views.inbound_bulk_preview, name="inbound_bulk_preview"),
    path("inbound/upload-template", views.download_inbound_upload_template),
    path("inbound/upload-template/", views.download_inbound_upload_template, name="inbound_upload_template"),
    path("inbound/upload-preview", views.inbound_upload_preview),
    path("inbound/upload-preview/", views.inbound_upload_preview, name="inbound_upload_preview"),
    path("inbound/upload-confirm", views.inbound_upload_confirm),
    path("inbound/upload-confirm/", views.inbound_upload_confirm, name="inbound_upload_confirm"),
    path("outbound", views.outbound_page),
    path("outbound/", views.outbound_page, name="outbound"),
    path("outbound/bulk-create", views.outbound_bulk_create),
    path("outbound/bulk-create/", views.outbound_bulk_create, name="outbound_bulk_create"),
    path("outbound/bulk-preview", views.outbound_bulk_preview),
    path("outbound/bulk-preview/", views.outbound_bulk_preview, name="outbound_bulk_preview"),
    path("outbound/upload-template", views.download_outbound_upload_template),
    path("outbound/upload-template/", views.download_outbound_upload_template, name="outbound_upload_template"),
    path("outbound/upload-preview", views.outbound_upload_preview),
    path("outbound/upload-preview/", views.outbound_upload_preview, name="outbound_upload_preview"),
    path("outbound/upload-confirm", views.outbound_upload_confirm),
    path("outbound/upload-confirm/", views.outbound_upload_confirm, name="outbound_upload_confirm"),
    path("history", views.history_page),
    path("history/", views.history_page, name="history"),
    path("history-admin", views.history_admin_page),
    path("history-admin/", views.history_admin_page, name="history_admin"),
    path("history-admin/<int:record_id>/edit", views.history_admin_edit),
    path("history-admin/<int:record_id>/edit/", views.history_admin_edit, name="history_admin_edit"),
    path("history-admin/<int:record_id>/delete", views.history_admin_delete),
    path("history-admin/<int:record_id>/delete/", views.history_admin_delete, name="history_admin_delete"),
    path("reagent-history", views.reagent_history_page),
    path("reagent-history/", views.reagent_history_page, name="reagent_history"),
    path("reagent-history/opened-at", views.reagent_history_opened_at),
    path("reagent-history/opened-at/", views.reagent_history_opened_at, name="reagent_history_opened_at"),
    path("reagent-history/parallel-at", views.reagent_history_parallel_at),
    path("reagent-history/parallel-at/", views.reagent_history_parallel_at, name="reagent_history_parallel_at"),
    path("reagent-history/old-new-lot", views.reagent_history_old_new_lot_save),
    path("reagent-history/old-new-lot/", views.reagent_history_old_new_lot_save, name="reagent_history_old_new_lot"),
]
