import os
from pathlib import Path

import psycopg

BASE_DIR = Path(__file__).resolve().parents[2]

PG_HOST = os.environ.get("REAGENT_PGHOST", "localhost")
PG_PORT = int(os.environ.get("REAGENT_PGPORT", "5432"))
PG_DBNAME = os.environ.get("REAGENT_PGDATABASE", "reagent")
PG_USER = os.environ.get("REAGENT_PGUSER", "postgres")
PG_PASSWORD = os.environ.get("REAGENT_PGPASSWORD", "tla123")


class HybridRow(dict):
    def __init__(self, columns, values):
        super().__init__(zip(columns, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


def _normalize_query(query: str):
    return query.replace("?", "%s")


class CursorWrapper:
    def __init__(self, cursor):
        self._cursor = cursor
        self.description = None
        self.rowcount = -1

    def execute(self, query, params=None):
        query = _normalize_query(query) if isinstance(query, str) else query
        self._cursor.execute(query, params)
        self.description = self._cursor.description
        self.rowcount = self._cursor.rowcount
        return self

    def executemany(self, query, params_seq):
        query = _normalize_query(query) if isinstance(query, str) else query
        self._cursor.executemany(query, params_seq)
        self.description = self._cursor.description
        self.rowcount = self._cursor.rowcount
        return self

    def fetchone(self):
        row = self._cursor.fetchone()
        return self._wrap_row(row)

    def fetchall(self):
        rows = self._cursor.fetchall()
        return [self._wrap_row(row) for row in rows]

    def _wrap_row(self, row):
        if row is None or isinstance(row, dict):
            return row
        if isinstance(row, tuple) and self.description:
            columns = [col.name for col in self.description]
            return HybridRow(columns, row)
        return row

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class ConnectionWrapper:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return CursorWrapper(self._connection.cursor())

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def ensure_column(cursor, table_name, column_name, ddl):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = %s
          AND column_name = %s
        """,
        (table_name, column_name),
    )
    if cursor.fetchone() is None:
        cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {ddl}")


def get_connection():
    conn = psycopg.connect(
        host=PG_HOST,
        port=PG_PORT,
        dbname=PG_DBNAME,
        user=PG_USER,
        password=PG_PASSWORD,
    )
    return ConnectionWrapper(conn)


def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS inventory (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            hazardous TEXT,
            part TEXT NOT NULL,
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT,
            expiry_date TEXT,
            spec TEXT,
            unit TEXT,
            reagent_type TEXT,
            equipment TEXT,
            vendor TEXT,
            safety_stock INTEGER NOT NULL DEFAULT 0,
            current_stock INTEGER NOT NULL DEFAULT 0,
            required_qty INTEGER NOT NULL DEFAULT 0
        )
        """
    )

    ensure_column(cursor, "inventory", "disposed_at", "disposed_at TEXT")
    ensure_column(cursor, "inventory", "disposal_reason", "disposal_reason TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "disposal_type", "disposal_type TEXT NOT NULL DEFAULT ''")
    ensure_column(cursor, "inventory", "opened_at", "opened_at TEXT")
    ensure_column(cursor, "inventory", "parallel_at", "parallel_at TEXT")
    ensure_column(cursor, "inventory", "base_item_name", "base_item_name TEXT")
    ensure_column(cursor, "inventory", "lot_status", "lot_status TEXT NOT NULL DEFAULT ''")

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS transaction_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inventory_id INTEGER NOT NULL REFERENCES inventory(id),
            tx_type TEXT NOT NULL,
            qty INTEGER NOT NULL,
            tx_date TEXT NOT NULL,
            note TEXT NOT NULL DEFAULT '',
            remaining_stock INTEGER NOT NULL DEFAULT 0,
            item_code TEXT NOT NULL,
            item_name TEXT NOT NULL,
            lot_no TEXT,
            part TEXT,
            unit TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    ensure_column(cursor, "transaction_history", "remaining_stock", "remaining_stock INTEGER NOT NULL DEFAULT 0")

    conn.commit()
    conn.close()
